name:                bookreator
version:             0.1.0.0
github:              "githubuser/bookreator"
license:             BSD3
author:              "Ian FRASER"
maintainer:          "ian.hc.fraser@gmail.com"
copyright:           "2019 Ian FRASER"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Dynamic book generator
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bookreator#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-home-modules
  - -Widentities
  - -Wredundant-constraints
  # Parallel by default
  - -j
  # Don't optimize by default (faster build time)
  - -O0

dependencies:
  - base >= 4.7 && < 5
  - hasbolt
  - bytestring
  - servant
  - servant-server
  - resource-pool

library:
  source-dirs: src

executables:
  bookreator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookreator

tests:
  bookreator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookreator
